// app
export const SET_USER_TYPE = "SET_USER_TYPE";

// layout
export const SET_SIDEBAR_OPEN = "SET_SIDEBAR_OPEN";

// auth
export const SAVE_USER_SIGN_IN = "SAVE_USER_SIGN_IN";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const SAVE_GET_USER_INFO = "SAVE_GET_USER_INFO";

// admin -> teacher
export const SAVE_GET_ALL_TEACHER = "SAVE_GET_ALL_TEACHER";
export const SAVE_SELECTED_TEACHER = "SAVE_SELECTED_TEACHER";
export const SAVE_CREATE_TEACHER = "SAVE_CREATE_TEACHER";
export const SAVE_DELETE_TEACHER = "SAVE_DELETE_TEACHER";
export const SAVE_UPDATE_TEACHER = "SAVE_UPDATE_TEACHER";
export const SET_DRAWER_TEACHER_VISIBLE = "SET_DRAWER_TEACHER_VISIBLE";
export const SET_PAGE_SIZE = "SET_PAGE_SIZE";

// teacher -> exam
export const TEACHER_SAVE_SELECTED_EXAM = "TEACHER_SAVE_SELECTED_EXAM";

// teacher -> manage exam paper
export const TEACHER_SET_PREVIEW_EXAM_PAPER_DRAWER_OPEN =
  "TEACHER_SET_PREVIEW_EXAM_PAPER_DRAWER_OPEN";
export const TEACHER_SAVE_GET_ALL_EXAM_PAPER =
  "TEACHER_SAVE_GET_ALL_EXAM_PAPER";
export const TEACHER_SAVE_SELECTED_EXAM_PAPER =
  "TEACHER_SAVE_SELECTED_EXAM_PAPER";
export const TEACHER_SAVE_CREATE_EXAM_PAPER = "TEACHER_SAVE_CREATE_EXAM_PAPER";
export const TEACHER_SAVE_DELETE_EXAM_PAPER = "TEACHER_SAVE_DELETE_EXAM_PAPER";
export const TEACHER_SAVE_UPDATE_EXAM_PAPER = "TEACHER_SAVE_UPDATE_EXAM_PAPER";
export const TEACHER_SET_MODAL_EXAM_PAPER_VISIBLE =
  "TEACHER_SET_MODAL_EXAM_PAPER_VISIBLE";
export const TEACHER_SET_EXAM_PAPER_PAGE_SIZE =
  "TEACHER_SET_EXAM_PAPER_PAGE_SIZE";

// teacher -> manage exam room
export const TEACHER_SAVE_GET_ALL_EXAM_ROOM = "TEACHER_SAVE_GET_ALL_EXAM_ROOM";
export const TEACHER_SAVE_SELECTED_EXAM_ROOM =
  "TEACHER_SAVE_SELECTED_EXAM_ROOM";
export const TEACHER_SAVE_CREATE_EXAM_ROOM =
  "SAVE_CREATE_TEACHER_SAVE_CREATE_EXAM_ROOMEXAM_ROOM";
export const TEACHER_SAVE_DELETE_EXAM_ROOM = "TEACHER_SAVE_DELETE_EXAM_ROOM";
export const TEACHER_SAVE_UPDATE_EXAM_ROOM = "TEACHER_SAVE_UPDATE_EXAM_ROOM";
export const TEACHER_SET_MODAL_EXAM_ROOM_VISIBLE =
  "TEACHER_SET_MODAL_EXAM_ROOM_VISIBLE";
export const TEACHER_SET_EXAM_ROOM_PAGE_SIZE =
  "TEACHER_SET_EXAM_ROOM_PAGE_SIZE";

// teacher -> manage student
export const TEACHER_SAVE_GET_ALL_STUDENT = "TEACHER_SAVE_GET_ALL_STUDENT";
export const TEACHER_SAVE_SELECTED_STUDENT = "TEACHER_SAVE_SELECTED_STUDENT";
export const TEACHER_SAVE_CREATE_STUDENT =
  "SAVE_CREATE_TEACHER_SAVE_CREATE_STUDENTSTUDENT";
export const TEACHER_SAVE_DELETE_STUDENT = "TEACHER_SAVE_DELETE_STUDENT";
export const TEACHER_SAVE_UPDATE_STUDENT = "TEACHER_SAVE_UPDATE_STUDENT";
export const TEACHER_SET_MODAL_STUDENT_VISIBLE =
  "TEACHER_SET_MODAL_STUDENT_VISIBLE";
export const TEACHER_SET_STUDENT_PAGE_SIZE = "TEACHER_SET_STUDENT_PAGE_SIZE";

// teacher -> manage question
export const TEACHER_SAVE_GET_ALL_QUESTION = "TEACHER_SAVE_GET_ALL_QUESTION";
export const TEACHER_SAVE_SELECTED_QUESTION = "TEACHER_SAVE_SELECTED_QUESTION";
export const TEACHER_SAVE_CREATE_QUESTION = "TEACHER_SAVE_CREATE_QUESTION";
export const TEACHER_SAVE_DELETE_QUESTION = "TEACHER_SAVE_DELETE_QUESTION";
export const TEACHER_SAVE_UPDATE_QUESTION = "TEACHER_SAVE_UPDATE_QUESTION";
export const TEACHER_SET_DRAWER_QUESTION_VISIBLE =
  "TEACHER_SET_DRAWER_QUESTION_VISIBLE";

// teacher -> manage examination
export const TEACHER_SAVE_GET_ALL_EXAMINATION = "TEACHER_SAVE_GET_ALL_QUESTION";
export const TEACHER_SAVE_SELECTED_EXAMINATION =
  "TEACHER_SAVE_SELECTED_QUESTION";
export const TEACHER_SAVE_CREATE_EXAMINATION = "TEACHER_SAVE_CREATE_QUESTION";
export const TEACHER_SAVE_DELETE_EXAMINATION = "TEACHER_SAVE_DELETE_QUESTION";
export const TEACHER_SAVE_UPDATE_EXAMINATION = "TEACHER_SAVE_UPDATE_QUESTION";
export const TEACHER_SET_EXAMINATION_PAGE_SIZE =
  "TEACHER_SET_EXAMINATION_PAGE_SIZE";
export const TEACHER_SET_MODAL_EXAM_PAPER_OPEN =
  "TEACHER_SET_MODAL_EXAM_PAPER_OPEN";
export const TEACHER_SET_LIST_EXAM_ROOM = "TEACHER_SET_LIST_EXAM_ROOM";

// teacher -> manage protor
export const TEACHER_SAVE_GET_ALL_PROTOR = "TEACHER_SAVE_GET_ALL_PROTOR";
export const TEACHER_SAVE_SELECTED_PROTOR = "TEACHER_SAVE_SELECTED_PROTOR";
export const TEACHER_SAVE_CREATE_PROTOR =
  "SAVE_CREATE_TEACHER_SAVE_CREATE_PROTORPROTOR";
export const TEACHER_SAVE_DELETE_PROTOR = "TEACHER_SAVE_DELETE_PROTOR";
export const TEACHER_SAVE_UPDATE_PROTOR = "TEACHER_SAVE_UPDATE_PROTOR";
export const TEACHER_SET_MODAL_PROTOR_VISIBLE =
  "TEACHER_SET_MODAL_PROTOR_VISIBLE";
export const TEACHER_SET_PROTOR_PAGE_SIZE = "TEACHER_SET_PROTOR_PAGE_SIZE";
export const TEACHER_SET_CREATE_EXAMINATION_STEP =
  "TEACHER_SET_CREATE_EXAMINATION_STEP";
